create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null default '',
    price numeric(12, 2) not null default 0 check (price >= 0),
    original_price numeric(12, 2) not null default 0 check (original_price >= 0),
    sale_price numeric(12, 2) not null default 0 check (sale_price >= 0),
    image text not null default '',
    description text not null default '',
    size text not null default '',
    color text not null default '',
    stock integer not null default 0 check (stock >= 0),
    parent_id bigint references public.products(id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists products_parent_id_idx on public.products(parent_id);

create table if not exists public.store_settings (
    key text primary key,
    value text not null default '',
    updated_at timestamptz not null default now()
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    customerName text,
    phone text not null,
    location text not null,
    address text,
    items text not null default '[]',
    total numeric(12, 2) not null default 0 check (total >= 0),
    status text not null default 'new' check (status in ('new', 'confirmed', 'shipped', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    product_id bigint not null,
    product_name text not null,
    quantity integer not null check (quantity > 0),
    price numeric(12, 2) not null check (price >= 0),
    original_price numeric(12, 2) not null default 0 check (original_price >= 0)
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);

insert into storage.buckets (id, name, public)
values ('store-images', 'store-images', true)
on conflict (id) do update set public = excluded.public;

alter table public.products add column if not exists original_price numeric(12, 2) not null default 0;
alter table public.products add column if not exists sale_price numeric(12, 2) not null default 0;
alter table public.order_items add column if not exists original_price numeric(12, 2) not null default 0;
update public.products set sale_price = price where sale_price = 0 and price > 0;
update public.products set original_price = sale_price where original_price = 0;
